(define-project-type maven (generic) (look-for "pom.xml")
  :relevant-files ("\\.java" "\\.html" "\\.jsp" "\\.css" "\\.js" "\\.xml")
  :irrelevant-files ("target/"))
(define-project-type emacs.d (generic)
  (and (look-for "init.el") (look-for "vendor"))
  :relevant-files ("\\.el" "README" "\\.txt")
  :irrelevant-files ("auto-save-list/" "backups/"))
(define-project-type grails (generic) (look-for "grails-app")
  :relevant-files ("\\.groovy" "\\.gsp" "\\.java" "\\.html" "\\.jsp" "\\.css" "\\.js" "\\.xml")
  :irrelevant-files ("target"))
(define-project-type clojure (generic) (look-for "project.clj")
  :relevant-files ("\\.clj" "\\.jsp" "\\.css" "\\.js" "\\.xml")
  :irrelevant-files ("lib/" "classes/"))

